#!/bin/bash
#
# Munch ... create a bootable iso with persistence
# by Mr Green
# 

set -o nounset

usage()
{
printf "Usage: %s: [sdx] [iso_file_name] \n" $(basename $0) >&2
exit 2
}

# test for number of args
[ $# -ne 2 ] && usage && exit 2

# Is $1 a block device?
[[ -b /dev/${1} ]] && usb_device=/dev/${1} || usage

# Is $2 a valid filename?
[[ -f ${2} ]] && iso_name=${2} || usage

# Path to syslinux
usb_syslinux=/mnt/usb/arch/boot/syslinux

# Mount,loop,copy
mkdir -p /mnt/{usb,iso}
mount -o loop ${iso_name} /mnt/iso
mount ${usb_device}1 /mnt/usb
cp -r /mnt/iso/* /mnt/usb

# Adjust syslinux and create persistence
extlinux --install ${usb_syslinux}
dd bs=440 conv=notrunc count=1 if=/usr/lib/syslinux/mbr.bin of=${usb_device}

# Boot device and create persistence  
usb_uuid="/dev/disk/by-uuid/$(lsblk -no UUID ${usb_device}1)"
sed -i "s|label.* |device=${usb_uuid} cow_device=${usb_uuid} |" ${usb_syslinux}/syslinux.cfg

# Clean up
umount /mnt/{usb,iso}
rmdir /mnt/usb
rmdir /mnt/iso
